In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split

In [8]:
data = pd.read_csv('data.csv')

In [9]:
data.head()

,Unnamed,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,y
0,X21.V1.791,135,190,229,223,192,125,55,-9,-33,...,-17,-15,-31,-77,-103,-127,-116,-83,-51,4
1,X15.V1.924,386,382,356,331,320,315,307,272,244,...,164,150,146,152,157,156,154,143,129,1
2,X8.V1.1,-32,-39,-47,-37,-32,-36,-57,-73,-85,...,57,64,48,19,-12,-30,-35,-35,-36,5
3,X16.V1.60,-105,-101,-96,-92,-89,-95,-102,-100,-87,...,-82,-81,-80,-77,-85,-77,-72,-69,-65,5
4,X20.V1.54,-9,-65,-98,-102,-78,-48,-16,0,-21,...,4,2,-12,-32,-41,-65,-83,-89,-73,5

In [10]:
data.drop('Unnamed', axis=1, inplace=True)
display(data.head())

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X170,X171,X172,X173,X174,X175,X176,X177,X178,y
0,135,190,229,223,192,125,55,-9,-33,-38,...,-17,-15,-31,-77,-103,-127,-116,-83,-51,4
1,386,382,356,331,320,315,307,272,244,232,...,164,150,146,152,157,156,154,143,129,1
2,-32,-39,-47,-37,-32,-36,-57,-73,-85,-94,...,57,64,48,19,-12,-30,-35,-35,-36,5
3,-105,-101,-96,-92,-89,-95,-102,-100,-87,-79,...,-82,-81,-80,-77,-85,-77,-72,-69,-65,5
4,-9,-65,-98,-102,-78,-48,-16,0,-21,-59,...,4,2,-12,-32,-41,-65,-83,-89,-73,5

In [11]:
data['y'] = [0 if x > 1 else x for x in data['y']]

In [12]:
data['y'].head(
  10
)

0    0
1    1
2    0
3    0
4    0
5    0
6    0
7    0
8    1
9    0
Name: y, dtype: int64

In [13]:
X_train,X_test,y_train,y_test = train_test_split(data.drop('y', axis=1), data['y'], test_size=0.2, random_state=42)

In [14]:
X_train

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X169,X170,X171,X172,X173,X174,X175,X176,X177,X178
11351,-66,-75,-95,-120,-141,-164,-172,-176,-192,-244,...,6,26,50,82,107,135,144,81,-30,-117
11220,-77,-50,-36,-72,-125,-138,-139,-130,-95,-38,...,-48,-72,-94,-101,-76,-33,12,63,77,49
3403,-74,-67,-58,-51,-43,-28,-23,-20,-19,-27,...,22,13,12,14,30,43,57,68,74,70
3827,17,20,24,29,34,34,37,37,33,29,...,72,71,73,72,72,79,82,83,81,69
5613,31,30,45,60,20,15,8,14,-3,-21,...,-40,38,53,73,55,75,55,11,-15,-77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,27,33,29,33,27,22,18,26,24,7,...,4,5,9,13,17,21,22,5,-5,-5
5191,-95,-140,-183,-209,-242,-259,-261,-244,-202,-146,...,273,237,204,162,131,95,48,14,-14,-42
5390,90,26,-58,-157,-251,-303,-285,-223,-149,-81,...,-108,-91,-76,-52,-8,28,37,15,-26,-72
860,91,79,55,21,-3,-14,-7,20,59,87,...,161,138,119,119,139,167,201,223,232,229
7270,-46,16,40,38,18,13,-3,-52,-12,21,...,-44,-37,-6,4,-9,-18,-31,-54,-80,-90

In [15]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X_train, y_train)

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_res, y_res)  
y_pred = rf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(f1_score(y_test, y_pred, average='weighted'))
print(accuracy_score(y_test, y_pred))

[[1782   53]
 [   9  456]]
0.9734887993857219
0.9730434782608696

In [18]:
print(accuracy_score(y_train, rf.predict(X_train)))

1.0

In [19]:
rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    min_samples_split=10,
    min_samples_leaf=4,
    criterion='entropy',
    class_weight=None,
    random_state=42,
    n_jobs=-1
)
rf.fit(X_res, y_res)
y_pred = rf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(f1_score(y_test, y_pred, average='weighted'))
print(accuracy_score(y_test, y_pred))

[[1791   44]
 [  19  446]]
0.9728732860639682
0.9726086956521739

In [20]:
print(accuracy_score(y_train, rf.predict(X_train)))

0.9956521739130435

# svm

In [22]:
from sklearn.svm import SVC
svm = SVC(kernel='rbf', C=1, gamma='scale', random_state=42)
svm.fit(X_res, y_res)
y_pred = svm.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(f1_score(y_test, y_pred, average='weighted'))
print(accuracy_score(y_test, y_pred))

[[1801   34]
 [  14  451]]
0.9792929375254694
0.9791304347826087

In [24]:
print(accuracy_score(y_train, svm.predict(X_train)))

0.9791304347826087